name: Update Unico SDK in Target Repo

on:
  schedule:
    - cron: "0 9 */10 * *"    # A cada 10 dias, às 9h UTC
  workflow_dispatch:       # Permite rodar manualmente

jobs:
  update-sdk:
    runs-on: ubuntu-latest

    steps:
      # 1️⃣ Checkout do repositório destino (target-repo)
      - name: Checkout destino
        uses: actions/checkout@v4
        with:
          repository: unico-labs/unico-sdk-poc-vuejs
          token: ${{ secrets.TARGET_REPO_PAT }}
          path: target-repo
          persist-credentials: false

      # 2️⃣ Configurar Python
      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      # 3️⃣ Instalar dependências Python
      - name: Install Python dependencies
        run: pip install requests beautifulsoup4

      # 4️⃣ Instalar GitHub CLI
      - name: Install GitHub CLI
        run: |
          sudo apt update
          sudo apt install gh -y
      
      # 4.1️⃣ Autenticar o Git com o token
      - name: Authenticate Git & GitHub CLI
        env:
          GH_TOKEN: ${{ secrets.TARGET_REPO_PAT }}
        run: |
          gh auth setup-git

      # 5️⃣ Rodar script de atualização
      - name: Run update script
        env:
          GITHUB_TOKEN: ${{ secrets.TARGET_REPO_PAT }}
        working-directory: ./target-repo
        run: python scripts/update_unico_target.py
